module hello
{
    interface EventDispatcher : com::sun::star::uno::XInterface
    {
        boolean processOpenEvent([in] com::sun::star::sheet::XSpreadsheetDocument xSpreadsheetDocument);
        boolean processSaveEvent([in] com::sun::star::sheet::XSpreadsheetDocument xSpreadsheetDocument);
        boolean processCloseEvent([in] com::sun::star::sheet::XSpreadsheetDocument xSpreadsheetDocument);
        void processChangeEvent([in] com::sun::star::sheet::XSpreadsheetDocument xSpreadsheetDocument);
        void processAfterSaveEvent([in] com::sun::star::sheet::XSpreadsheetDocument xSpreadsheetDocument);
    };
};
